-- NOTE:
-- This migration originally failed because "written_quotes" already existed in the database.
-- The database was corrected outside Prisma and this migration was marked as applied with 0 steps.
-- To keep migration history replayable (shadow DB) and avoid drift, this migration is intentionally a no-op.
